In [16]:
symbols(24)

Equity(24, symbol=u'AAPL', asset_name=u'APPLE INC', exchange=u'NASDAQ', start_date=Timestamp('2002-01-01 00:00:00+0000', tz='UTC'), end_date=Timestamp('2017-05-25 00:00:00+0000', tz='UTC'), first_traded=None, auto_close_date=Timestamp('2017-05-31 00:00:00+0000', tz='UTC'), exchange_full=u'NASDAQ GLOBAL SELECT MARKET')

In [15]:
apple_price_this_year = get_pricing(24, start_date='2017-01-01', end_date='2017-05-25')["price"]

In [12]:
import pandas as pd
import matplotlib.pyplot as plt

In [48]:
apple_price_this_year

apple_price_mvag_5d = pd.rolling_mean(apple_price_this_year, window=5).rename('mvag_past_5d')
apple_price_mvag_10d = pd.rolling_mean(apple_price_this_year, window=10).rename('mvag_past_10d')
apple_price_mvag_20d = pd.rolling_mean(apple_price_this_year, window=20).rename('mvag_past_20d')
apple_price_mvag_30d = pd.rolling_mean(apple_price_this_year, window=30).rename('mvag_past_30d')
apple_price_mvag_60d = pd.rolling_mean(apple_price_this_year, window=60).rename('mvag_past_60d')

apple_price_this_year_mvag = pd.concat([apple_price_this_year, 
            apple_price_mvag_5d, 
          apple_price_mvag_10d,
          apple_price_mvag_20d,
          apple_price_mvag_30d,
          apple_price_mvag_60d], axis=1
         )
apple_price_this_year_mvag

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with
	Series.rolling(window=5,center=False).mean()
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with
	Series.rolling(window=10,center=False).mean()
  after removing the cwd from sys.path.
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with
	Series.rolling(window=20,center=False).mean()
  """
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with
	Series.rolling(window=30,center=False).mean()

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: pd.rolling_mean is deprecated for Series and will be removed in a future version, replace with
	Series.rolling(window=60,center=False).mean()
  import sys

,price,mvag_past_5d,mvag_past_10d,mvag_past_20d,mvag_past_30d,mvag_past_60d
2017-01-03 00:00:00+00:00,115.163,NaN,NaN,NaN,NaN,NaN
2017-01-04 00:00:00+00:00,115.044,NaN,NaN,NaN,NaN,NaN
2017-01-05 00:00:00+00:00,115.629,NaN,NaN,NaN,NaN,NaN
2017-01-06 00:00:00+00:00,116.918,NaN,NaN,NaN,NaN,NaN
2017-01-09 00:00:00+00:00,117.999,116.1506,NaN,NaN,NaN,NaN
2017-01-10 00:00:00+00:00,118.108,116.7396,NaN,NaN,NaN,NaN
2017-01-11 00:00:00+00:00,118.733,117.4774,NaN,NaN,NaN,NaN
2017-01-12 00:00:00+00:00,118.247,118.0010,NaN,NaN,NaN,NaN
2017-01-13 00:00:00+00:00,118.039,118.2252,NaN,NaN,NaN,NaN
2017-01-17 00:00:00+00:00,118.981,118.4216,117.2861,NaN,NaN,NaN
2017-01-18 00:00:00+00:00,118.981,118.5962,117.6679,NaN,NaN,NaN
2017-01-19 00:00:00+00:00,118.763,118.6022,118.0398,NaN,NaN,NaN
2017-01-20 00:00:00+00:00,118.991,118.7510,118.3760,NaN,NaN,NaN
2017-01-23 00:00:00+00:00,119.080,118.9592,118.5922,NaN,NaN,NaN
2017-01-24 00:00:00+00:00,118.971,118.9572,118.6894,NaN,NaN,NaN
2017-01-25 00:00:00+00:00,120.875,119.3360,118.9661,NaN,NaN,NaN
2017-01-26 00:00:00+00:00,120.905,119.7644,119.1833,NaN,NaN,NaN
2017-01-27 00:00:00+00:00,120.696,120.1054,119.4282,NaN,NaN,NaN
2017-01-30 00:00:00+00:00,120.548,120.3990,119.6791,NaN,NaN,NaN
2017-01-31 00:00:00+00:00,120.280,120.6608,119.8090,118.54755,NaN,NaN
2017-02-01 00:00:00+00:00,127.667,122.0192,120.6776,119.17275,NaN,NaN
2017-02-02 00:00:00+00:00,127.428,123.3238,121.5441,119.79195,NaN,NaN
2017-02-03 00:00:00+00:00,127.994,124.7834,122.4444,120.41020,NaN,NaN
2017-02-06 00:00:00+00:00,129.214,126.5166,123.4578,121.02500,NaN,NaN
2017-02-07 00:00:00+00:00,130.404,128.5414,124.6011,121.64525,NaN,NaN
2017-02-08 00:00:00+00:00,130.930,129.1940,125.6066,122.28635,NaN,NaN
2017-02-09 00:00:00+00:00,131.876,130.0836,126.7037,122.94350,NaN,NaN
2017-02-10 00:00:00+00:00,131.577,130.8002,127.7918,123.61000,NaN,NaN
2017-02-13 00:00:00+00:00,132.742,131.5058,129.0112,124.34515,NaN,NaN
2017-02-14 00:00:00+00:00,134.455,132.3160,130.4287,125.11885,122.507933,NaN
...,...,...,...,...,...,...
2017-04-13 00:00:00+00:00,140.470,141.6094,142.4887,141.80160,140.834333,135.140483
2017-04-17 00:00:00+00:00,141.247,141.3086,142.3055,141.89720,140.902733,135.515217
2017-04-18 00:00:00+00:00,140.639,140.9202,142.0585,141.88425,140.965800,135.876017
2017-04-19 00:00:00+00:00,140.082,140.7290,141.6512,141.92460,141.004633,136.226050
2017-04-20 00:00:00+00:00,141.864,140.8604,141.4948,141.97535,141.118800,136.607600
2017-04-21 00:00:00+00:00,141.685,141.1034,141.3564,142.04255,141.237967,136.954433
2017-04-24 00:00:00+00:00,143.030,141.4600,141.3843,142.19145,141.386367,137.323183
2017-04-25 00:00:00+00:00,143.936,142.1194,141.5198,142.37320,141.563633,137.710517
2017-04-26 00:00:00+00:00,143.069,142.7168,141.7229,142.36570,141.718967,138.085867
2017-04-27 00:00:00+00:00,143.189,142.9818,141.9211,142.34780,141.829500,138.467683
2017-04-28 00:00:00+00:00,143.050,143.2548,142.1791,142.33390,141.927433,138.724067
2017-05-01 00:00:00+00:00,145.958,143.8404,142.6502,142.47785,142.148200,139.032900
2017-05-02 00:00:00+00:00,146.864,144.4260,143.2727,142.66560,142.347067,139.347400
2017-05-03 00:00:00+00:00,146.455,145.1032,143.9100,142.78060,142.586400,139.634750
2017-05-04 00:00:00+00:00,145.938,145.6530,144.3174,142.90610,142.756033,139.893650
2017-05-05 00:00:00+00:00,148.348,146.7126,144.9837,143.17005,143.022933,140.183950
2017-05-08 00:00:00+00:00,152.381,147.9972,145.9188,143.65155,143.433900,140.525700
2017-05-09 00:00:00+00:00,153.347,149.2938,146.8599,144.18985,143.868767,140.888533
2017-05-10 00:00:00+00:00,152.630,150.5288,147.8160,144.76945,144.182467,141.220000
2017-05-11 00:00:00+00:00,153.940,152.1292,148.8911,145.40610,144.528900,141.544750
2017-05-12 00:00:00+00:00,156.100,153.6796,150.1961,146.18760,144.954633,141.897200
2017-05-15 00:00:00+00:00,155.700,154.3434,151.1703,146.91025,145.375333,142.245717
2017-05-16 00:00:00+00:00,155.470,154.7680,152.0309,147.65180,145.787367,142.584350
2017-05-17 00:00:00+00:00,150.200,154.2820,152.4054,148.15770,145.988867,142.818883
2017-05-18 00:00:00+00:00,152.540,154.0020,153.0656,148.69150,146.292600,143.085450
2017-05-19 00:00:00+00:00,153.050,153.3920,153.5358,149.25975,146.625300,143.370133
2017-05-22 00:00:00+00:00,153.960,153.0440,153.6937,149.80625,146.998933,143.668000
2017-05-23 00:00:00+00:00,153.800,152.7100,153.7390,150.29945,147.372900,143.958550
2017-05-24 00:00:00+00:00,153.300,153.3300,153.8060,150.81100,147.781633,144.239767
2017-05-25 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
plt.plot(apple_price_this_year.index, apple_price_this_year.values)
plt.plot(apple_price_mvag_30d.index, apple_price_mvag_30d.values)

In [47]:
apple_price_1d_return = apple_price_this_year.pct_change(-1).rename('return_next_1d')
apple_price_2d_return = apple_price_this_year.pct_change(-2).rename('return_next_2d')
apple_price_3d_return = apple_price_this_year.pct_change(-3).rename('return_next_3d')
apple_price_4d_return = apple_price_this_year.pct_change(-4).rename('return_next_4d')
apple_price_5d_return = apple_price_this_year.pct_change(-5).rename('return_next_5d')
apple_price_10d_return = apple_price_this_year.pct_change(-10).rename('return_next_10d')
apple_price_20d_return = apple_price_this_year.pct_change(-20).rename('return_next_20d')
apple_price_30d_return = apple_price_this_year.pct_change(-30).rename('return_next_30d')
apple_price_60d_return = apple_price_this_year.pct_change(-60).rename('return_next_60d')

apple_price_this_year_return = pd.concat([apple_price_1d_return, 
                                        apple_price_2d_return,
                                        apple_price_3d_return,
                                        apple_price_4d_return,
                                        apple_price_5d_return,
                                        apple_price_10d_return,
                                        apple_price_20d_return,
                                        apple_price_30d_return,
                                        apple_price_60d_return])

In [37]:
?pct_change()

Object `pct_change` not found.